apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: global-infra
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: ops-test
  namespace: infra
spec:
  rules:
  - host: ops-test.zilliz.cc
    http:
      paths:
      - backend:
          service:
            name: ops-test
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ops-test.zilliz.cc
